name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: lts/*
    - run: |
        npm install -g appium
        npm install --no-package-lock
        npm run build
      name: Install dev dependencies
    - run: npm run lint
      name: Linter
    - run: npm run test
      name: Unit Test
    - run: |
        rm -rf node_modules
        npm prune --omit=dev --omit=peer --no-package-lock
      name: Remove dev dependencies and appium peer dependency
    - run: npm shrinkwrap --omit=dev --omit=peer
      name: Create shrinkwrap
    - run: npm install --only=dev --no-package-lock
      name: Install dev dependencies for the release
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Release
