name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - run: |
        npm install -g appium
        npm install --no-package-lock
        npm run build
      name: Install dev dependencies
    - run: npm run lint
      name: Linter
    - run: npm run test
      name: Unit Test
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Release
