name: Unit Tests

on: [pull_request, push]

env:
  CI: true

permissions:
  contents: read

jobs:
  prepare_matrix:
    uses: appium/appium-workflows/.github/workflows/node-lts-matrix.yml@main

  test:
    needs:
    - prepare_matrix
    strategy:
      matrix:
        node-version: ${{ fromJSON(needs.prepare_matrix.outputs.versions) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - name: SocketDev Security Check
      uses: SocketDev/action@v1
      with:
        mode: firewall-free
    - name: Install dependencies
      run: sfw npm i
    - name: Build packages
      run: npm run build
    - name: Run linter
      run: npm run lint
    - name: Run unit tests
      run: npm run test
